server:
  port: ${PORT:8082}

spring:
  application:
    name: lookup-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/sugam?connectionTimeZone=UTC}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root123}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true